import { Right, Terms } from '../lib/model';
import { Waterfall } from './waterfall';

export const RIGHTS: Right[] = [
  {
    id: 'originPatheTheatricalDistributionFees',
    orgId: 'pathe',
    orgName: 'Pathé',
    title: 'Commission Salles',
    percentage: 0.175,
    termsIds: ['originTheatrical'],
    parentIds: ['originTheatrical'],
  },
  {
    id: 'originPartnerTheatricalDistributionFees',
    orgId: 'partner',
    orgName: 'Partenaire',
    title: 'Commission Salles',
    percentage: 0.2121212121,
    termsIds: ['originTheatrical'],
    parentIds: ['originPatheTheatricalDistributionFees'],
  },
  {
    id: 'originPatheTvDistributionFees',
    orgId: 'pathe',
    orgName: 'Pathé',
    title: 'Commission TV',
    percentage: 0,
    termsIds: ['originTv'],
    parentIds: ['originTv'],
  },
  {
    id: 'originPartnerTvDistributionFees',
    orgId: 'partner',
    orgName: 'Partenaire',
    title: 'Commission TV',
    percentage: 0,
    termsIds: ['originTv'],
    parentIds: ['originPatheTvDistributionFees'],
  },
  {
    id: 'originPatheVideoDistributionFees',
    orgId: 'pathe',
    orgName: 'Pathé',
    title: 'Commission Vidéo',
    percentage: 0.175,
    termsIds: ['originVideo'],
    parentIds: ['originVideo'],
  },
  {
    id: 'originPartnerVideoDistributionFees',
    orgId: 'partner',
    orgName: 'Partenaire',
    title: 'Commission Vidéo',
    percentage: 0.2121212121,
    termsIds: ['originVideo'],
    parentIds: ['originPatheVideoDistributionFees'],
  },
  {
    id: 'originPatheVodDistributionFees',
    orgId: 'pathe',
    orgName: 'Pathé',
    title: 'Commission VOD',
    percentage: 0.175,
    termsIds: ['originVod'],
    parentIds: ['originVod'],
  },
  {
    id: 'originPartnerVodDistributionFees',
    orgId: 'partner',
    orgName: 'Partenaire',
    title: 'Commission VOD',
    percentage: 0.2121212121,
    termsIds: ['originVod'],
    parentIds: ['originPatheVodDistributionFees'],
  },
  {
    id: 'rowAllPatheRightsDistributionFees',
    title: 'Commission Export',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.125,
    termsIds: ['rowAllRights'],
    parentIds: ['rowAllRights'],
  },
  {
    id: 'rowAllPartnerRightsDistributionFees',
    title: 'Commission Export',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 0.14285714,
    termsIds: ['rowAllRights'],
    parentIds: ['rowAllPatheRightsDistributionFees'],
  },
  {
    id: 'originTheatricalExpenses',
    title: "Frais d'édition Salles",
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 1,
    termsIds: ['originTheatrical'],
    parentIds: ['originPartnerTheatricalDistributionFees'],
    conditions: [
      {
        kind: 'right',
        max: 1150000,
        rightId: 'originTheatricalExpenses',
      }
    ],
  },
  {
    id: 'originVideoExpenses',
    title: "Frais d'édition Vidéo",
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 1,
    termsIds: ['originVideo'],
    parentIds: ['originPartnerVideoDistributionFees'],
    conditions: [
      {
        kind: 'right',
        max: 137344,
        rightId: 'originVideoExpenses',
      },
    ],
  },
  {
    id: 'rowExpenses',
    title: 'Frais Export',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 1,
    termsIds: ['rowAllRights'],
    parentIds: ['rowAllPartnerRightsDistributionFees'],
    conditions: [
      {
        kind: 'right',
        max: 56000,
        rightId: 'rowExpenses',
      },
    ],
  },
  {
    id: 'MG',
    title: 'Minimum Garanti',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 1,
    termsIds: ['originTheatrical', 'originVideo', 'originVod', 'rowAllRights'],
    parentIds: ['originTheatricalExpenses', 'originVideoExpenses', 'originPartnerVodDistributionFees', 'rowExpenses'],
    conditions: [
      {
        kind: 'right',
        max: 1_500_000,
        rightId: 'MG',
      },
    ],
  },
  {
    id: 'RNPPAydTheatrical',
    title: 'RNPP AYD Salles',
    orgId: 'AYD',
    orgName: 'Ayants droit',
    parentIds: ['MG'],
    termsIds: ['originTheatrical'],
    percentage: 0.62,
  },
  {
    id: 'RNPPAydVideo',
    title: 'RNPP AYD Vidéo',
    orgId: 'AYD',
    orgName: 'Ayants droit',
    parentIds: ['MG'],
    termsIds: ['originVideo'],
    percentage: 0.62,
  },
  {
    id: 'RNPPAydVod',
    title: 'RNPP AYD VOD',
    orgId: 'AYD',
    orgName: 'Ayants droit',
    parentIds: ['MG'],
    termsIds: ['originVod'],
    percentage: 0.62,
  },
  {
    id: 'RNPPAydRow',
    title: 'RNPP AYD Export',
    orgId: 'AYD',
    orgName: 'Ayants droit',
    parentIds: ['MG'],
    termsIds: ['rowAllRights'],
    percentage: 0.62,
  },
  {
    id: 'RNPPAydTv',
    title: 'RNPP AYD TV',
    orgId: 'AYD',
    orgName: 'Ayants droit',
    percentage: 0.57,
    parentIds: ['originPartnerTvDistributionFees'],
    termsIds: ['originTv'],
  },
  {
    id: 'tVBroadcasterRNPP',
    title: 'RNPP Chaîne TV',
    orgId: 'tvBroadcaster',
    orgName: 'Chaîne TV',
    percentage: 0.08,
    parentIds: ['originPartnerTvDistributionFees'],
    termsIds: ['originTv'],
  },
  {
    id: 'RNPPpatheTheatrical',
    title: 'RNPP Pathé Salles',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['originTheatrical'],
  },
  {
    id: 'RNPPpatheVideo',
    title: 'RNPP Pathé Vidéo',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['originVideo'],
  },
  {
    id: 'RNPPpatheVod',
    title: 'RNPP Pathé VOD',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['originVod'],
  },
  {
    id: 'RNPPpatheRow',
    title: 'RNPP Pathé Export',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['rowAllRights'],
  },
  {
    id: 'RNPPpatheTv',
    title: 'RNPP Pathé TV',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.175,
    parentIds: ['originPartnerTvDistributionFees'],
    termsIds: ['originTv'],
  },
  {
    id: 'RNPPPartnerTheatrical',
    title: 'RNPP Partenaire Salles',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['originTheatrical'],
  },
  {
    id: 'RNPPPartnerVideo',
    title: 'RNPP Partenaire Vidéo',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['originVideo'],
  },
  {
    id: 'RNPPPartnerVod',
    title: 'RNPP Partenaire VOD',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['originVod'],
  },
  {
    id: 'RNPPPartnerRow',
    title: 'RNPP Partenaire Export',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 0.19,
    parentIds: ['MG'],
    termsIds: ['rowAllRights'],
  },
  {
    id: 'RNPPPartnerTv',
    title: 'RNPP Partenaire TV',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 0.175,
    parentIds: ['originPartnerTvDistributionFees'],
    termsIds: ['originTv'],
  },
  {
    id: 'tVBroadcasterSupport',
    title: 'Soutien financier Chaîne TV',
    orgId: 'tvBroadcaster',
    orgName: 'Chaîne TV',
    percentage: 0.1,
    parentIds: ['prodFullSupport'],
    termsIds: ['theatricalSupport', 'videoSupport', 'tvSupport'],
  },
  {
    id: 'equitySupport',
    title: 'Soutien financier Fonds Equity',
    orgId: 'equity',
    orgName: 'Fonds Equity',
    percentage: 0.064,
    parentIds: ['prodFullSupport'],
    termsIds: ['theatricalSupport', 'videoSupport', 'tvSupport'],
  },
  {
    id: 'prodFullSupport',
    title: 'Soutien financier Producteur 100%',
    orgId: 'prod',
    orgName: 'Producteur',
    parentIds: ['theatricalSupport', 'videoSupport', 'tvSupport'],
    termsIds: ['theatricalSupport', 'videoSupport', 'tvSupport'],
    percentage: 1,
    conditions: [
      {
        kind: 'right',
        max: 150000,
        rightId: 'prodFullSupport',
      },
    ],
  },
  {
    id: 'prodFollowingSupport',
    title: 'Soutien financier Producteur 50%',
    orgId: 'prod',
    orgName: 'Producteur',
    percentage: 0.5,
    parentIds: ['prodFullSupport'],
    termsIds: ['theatricalSupport', 'videoSupport', 'tvSupport'],
  },
  {
    id: 'patheSupport',
    title: 'Soutien financier Pathé',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.168,
    parentIds: ['prodFullSupport'],
    termsIds: ['theatricalSupport', 'videoSupport', 'tvSupport'],
  },
  {
    id: 'partnerSupport',
    title: 'Soutien financier Pathé',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 0.168,
    parentIds: ['prodFullSupport'],
    termsIds: ['theatricalSupport', 'videoSupport', 'tvSupport'],
  },
  {
    id: 'patheBonusSupport',

    title: 'Majoration soutien financier Pathé',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 1,
    parentIds: ['bonusSupport'],
    termsIds: ['bonusSupport'],
  },
  {
    id: 'patheDistSupport',
    title: 'Soutien distributeur Pathé',
    orgId: 'pathe',
    orgName: 'Pathé',
    percentage: 0.5,
    parentIds: ['theatricalDistSupport', 'videoDistSupport'],
    termsIds: ['theatricalDistSupport', 'videoDistSupport'],
  },
  {
    id: 'partnerDistSupport',
    title: 'Soutien distributeur Partenaire',
    orgId: 'partner',
    orgName: 'Partenaire',
    percentage: 1,
    parentIds: ['patheDistSupport'],
    termsIds: ['theatricalDistSupport', 'videoDistSupport'],
  },
];

export const TERMS: Terms[] = [
  {
    id: 'originTheatrical',
    title: 'Exploitation Salles',
    territories: {
      included: ['France', 'Switzerland', 'Belgium'],
      excluded: [],
    },
    channels: {
      included: ['theatrical'],
      excluded: [],
    },
    type: 'origin',
  },
  {
    id: 'originTv',
    title: 'Exploitation TV',
    territories: {
      included: ['France', 'Switzerland', 'Belgium'],
      excluded: [],
    },
    channels: {
      included: ['pay-tv', 'free-tv'],
      excluded: [],
    },
    type: 'origin',
  },
  {
    id: 'originVideo',
    title: 'Exploitation Vidéo',
    territories: {
      included: ['France', 'Switzerland', 'Belgium'],
      excluded: [],
    },
    channels: {
      included: ['video'],
      excluded: [],
    },
    type: 'origin',
  },
  {
    id: 'originVod',
    title: 'Exploitation VOD',
    territories: {
      included: ['France', 'Switzerland', 'Belgium'],
      excluded: [],
    },
    channels: {
      included: ['est', 'pay-per-view', 'n-vod', 'a-vod', 'f-vod', 's-vod'],
      excluded: [],
    },
    type: 'origin',
  },
  {
    id: 'rowAllRights',
    title: 'Exploitation Export',
    territories: {
      included: ['World'],
      excluded: ['France', 'Switzerland', 'Belgium'],
    },
    channels: {
      included: ['all-rights'],
      excluded: [],
    },
    type: 'origin',
  },
  {
    id: 'theatricalSupport',
    title: 'Soutien financier salle',
    territories: {
      included: ['France'],
      excluded: [],
    },
    channels: {
      included: ['theatrical'],
      excluded: [],
    },
    type: 'support',
  },
  {
    id: 'videoSupport',
    title: 'Soutien financier vidéo',
    territories: {
      included: ['France'],
      excluded: [],
    },
    channels: {
      included: ['video'],
      excluded: [],
    },
    type: 'support',
  },
  {
    id: 'tvSupport',
    title: 'Soutien financier TV',
    territories: {
      included: ['France'],
      excluded: [],
    },
    channels: {
      included: ['pay-tv', 'free-tv'],
      excluded: [],
    },
    type: 'support',
  },
  {
    id: 'bonusSupport',
    title: 'Majoration soutien financier',
    territories: {
      included: ['France'],
      excluded: [],
    },
    channels: {
      included: ['pay-tv', 'free-tv'],
      excluded: [],
    },
    type: 'support',
  },
  {
    id: 'theatricalDistSupport',
    title: 'Soutien distributeur salle',
    territories: {
      included: ['France'],
      excluded: [],
    },
    channels: {
      included: ['theatrical'],
      excluded: [],
    },
    type: 'support',
  },
  {
    id: 'videoDistSupport',
    title: 'Soutien distributeur vidéo',
    territories: {
      included: ['France'],
      excluded: [],
    },
    channels: {
      included: ['video'],
      excluded: [],
    },
    type: 'support',
  },
];
export const WATERFALL: Waterfall = {
  id: 'withoutMG',
  type: 'scenario',
  name: 'Sans MG',
  orgId: '',
  simulations: [
    {
      name: 'crash',
      multiplier: 1,
      ticket: {
        amount: 650_000,
        price: 6.01,
      },
      terms: {
        originTheatrical: 1_690_000,
        originVideo: 187_406,
        originVod: 202_800,
        originTv: 450_000,
        rowAllRights: 550_000,
      },
    },
    {
      name: 'budget',
      multiplier: 1,
      ticket: {
        amount: 1_000_000,
        price: 6.01,
      },
      terms: {
        originTheatrical: 2_600_000,
        originVideo: 312_344,
        originVod: 299_000,
        originTv: 600_000,
        rowAllRights: 816_000,
      },
    },
    {
      name: 'succès',
      multiplier: 1,
      ticket: {
        amount: 1_300_000,
        price: 6.01,
      },
      terms: {
        originTheatrical: 3_380_000,
        originVideo: 624_688,
        originVod: 520_000,
        originTv: 800_000,
        rowAllRights: 1_790_000,
      },
    },
  ],
  terms: TERMS,
  rights: RIGHTS,
  investments: {
    pathe: 750_000,
    partner: 750_000,
  },
};
